#!/usr/bin/perl

use strict;
use warnings;
use CGI qw(:standard);
use Time::HiRes qw(gettimeofday);

my $client_time = param('client_time');

my $current_second = (localtime)[0];
my ($server_seconds, $server_microseconds) = gettimeofday();
my $server_miliseconds = int ($server_microseconds / 1000);
my $server_time = $server_seconds * 1000 + $server_miliseconds; 
my $miliseconds_until_next_game = 30_000 - (($current_second * 1000) % 30_000);
my $delta = $server_time - $client_time;
my $game_time = $client_time + $delta + $miliseconds_until_next_game;

warn "Server time: $server_time";
warn "Client time: $client_time";
warn "Game time:   $game_time";
warn "Delta:       $delta";
warn "Modulo:      $miliseconds_until_next_game";
warn "Current second: $current_second";

print header(), $game_time;
