#!/usr/bin/perl

use strict;
use warnings;
use CGI qw(:standard);
use Time::HiRes qw(gettimeofday);

my $client_time = param('client_time');

my ($server_seconds, $server_microseconds) = gettimeofday();
my $server_miliseconds = int ($server_microseconds / 1000);
my $server_time = $server_seconds * 1000 + $server_miliseconds;
my $miliseconds_until_next_game = ($server_time + 30000) % 30000;
my $delta = $server_time - $client_time;
my $game_time = $client_time + $delta + $miliseconds_until_next_game;

warn "Server time: $server_time";
warn "Client time: $client_time";
warn "Game time:   $game_time";

print header(), $game_time;
