#!/usr/bin/perl

use strict;
use warnings;
use CGI qw(:standard);
use Time::HiRes qw(gettimeofday);

my $client_time = param('client_time');

my ($server_seconds, $server_microseconds) = gettimeofday();
my $server_miliseconds = int ($server_microseconds / 1000);
my $server_time = $server_seconds * 1000 + $server_miliseconds;
my $miliseconds_until_next_game = $server_time  % 30000;
my $game_time = $server_time - $client_time + $miliseconds_until_next_game;

my $html = <<"END_HTML";
<p>Server Time: $server_time</p>
<p>Client Time: $client_time</p>
<p>Game Time:   $game_time</p>
END_HTML

print header(), start_html(), $html, end_html();
